on: push

name: pdf

jobs:
  ubuntu:
    runs-on: macos-latest
    steps:
      - name: chmod
        if: runner.os == 'macOS'
        run: |
          wget -q https://dl.google.com/chrome/mac/stable/GGRO/googlechrome.dmg
          pwd
          ls /
          sudo hdiutil attach googlechrome.dmg
      - uses: actions/checkout@v1
      - uses: r-lib/actions/setup-pandoc@v1
        with:
          pandoc-version: '2.7.3' 
      - uses: r-lib/actions/setup-r@master
      - name: Install dependencies
        run: |
          install.packages('remotes')
          remotes::install_deps(dependencies = TRUE)
        shell: Rscript {0}
      - name: pdf
        run: pagedown::chrome_print('test.Rmd', extra_args = c('--disable-gpu', '--no-sandbox'), verbose = 1)
        shell: Rscript {0}
