on: push

name: pdf

jobs:
  pdf:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v1
      - uses: r-lib/actions/setup-r@master
      - uses: ./.github/actions/setup-chromium
      - name: Install dependencies
        run: Rscript -e "install.packages('remotes')" -e "remotes::install_deps(dependencies = TRUE)"
      - name: pdf
        run: Rscript -e "pagedown::find_chrome()"
