on: push

name: pdf

jobs:
  pdf:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: r-lib/actions/setup-pandoc@v1
        with:
          pandoc-version: '2.7.3' 
      - uses: r-lib/actions/setup-r@master
      - name: Install dependencies
        run: Rscript -e "install.packages('remotes')" -e "remotes::install_deps(dependencies = TRUE)"
      - name: pdf
        run: pagedown::chrome_print('test.Rmd', extra_args = c('--disable-gpu', '--no-sandbox'), verbose = 1)
        shell: Rscript
